### ISSUE TITLE
Discrepancy between emmeans::joint_tests and geeasy::drop1

### ISSUE THREAD

**Issue by hugesingleton** [annennenne/geeasy#1]
Hello,
My goal was the assessment of the main and interaction effects of a simple, exemplary longitudinal model.

It's easy for full-likelihood methods, e.g. GLS, mixed models via the sequence of likelihood ratio tests, doing the type-3 analysis (like type-3 ANOVA in SAS). In case of GEE, we can only employ the Wald's approach to joint test of contrasts.

Currently there's such function in the famous emmeans package (for LS-means), but it gave me different results, than drop1.

Let me show an example:

I checked the joint_tests against drop1 from [geeasy ](https://cran.r-project.org/web/packages/geeasy/index.html) and it agrees only partially. I decided to report it anyway. I don't say the joint_tests has any problem, reporting the discrepancy just in case, for "cross-verification".

The data:
```
d <- structure(list(ID = c(1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 
4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 
9, 9, 10, 10, 10, 10), TimeOrd = structure(c(1L, 2L, 3L, 4L, 
1L, 2L, 3L, 4L, 1L, 2L, 3L, 4L, 1L, 2L, 3L, 4L, 1L, 2L, 3L, 4L, 
1L, 2L, 3L, 4L, 1L, 2L, 3L, 4L, 1L, 2L, 3L, 4L, 1L, 2L, 3L, 4L, 
1L, 2L, 3L, 4L), .Label = c("M0", "M1", "M2", "M3"), class = c("ordered", 
"factor")), Result = c(1, 1.1, 1.5, 2, 1.1, 1.1, 1.4, 3, 1.1, 
1.2, 1.7, 5, 1.5, 3, 4.6, 6, 2.3, 4.4, 5.5, 8, 2, 2.2, 2.3, 7, 
4.5, 1, 3, 7, 3.3, 4.4, 5.5, 5, 3, 4, 5, 8, 1.1, 2.2, 3.3, 5), 
    SucN = c(0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 
    0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 
    1, 1, 1, 1, 0), Time = structure(c(1L, 2L, 3L, 4L, 1L, 2L, 
    3L, 4L, 1L, 2L, 3L, 4L, 1L, 2L, 3L, 4L, 1L, 2L, 3L, 4L, 1L, 
    2L, 3L, 4L, 1L, 2L, 3L, 4L, 1L, 2L, 3L, 4L, 1L, 2L, 3L, 4L, 
    1L, 2L, 3L, 4L), .Label = c("M0", "M1", "M2", "M3"), class = "factor")), row.names = c(NA, 
40L), class = "data.frame")
```

And the test:
```
library(geepack)
library(emmeans)
library(geeasy)

> options(contrasts = c("contr.sum", "contr.poly"))

> m_geepack <- geeglm(SucN ~ Time * Result, family=binomial(link = "logit"), data=d, id=ID, corstr = "exchangeable", std.err="san.se")

> drop1(m_geepack,scope = SucN~Time*Result)
Single term deletions

Model:
SucN ~ Time * Result
            DF Wald Pr(>Chi)  
Time         3 6.49    0.090 .
Result       1 0.28    0.595  
Time:Result  3 7.22    0.065 .
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

> joint_tests(m_geepack)
 model term  df1 df2 F.ratio p.value
 Time          3 Inf   3.123  0.0250
 Result        1 Inf   0.282  0.5950
 Time:Result   3 Inf   2.406  0.0650
```
As we can see, it agrees well but only for Result and Time:Result. There is a disagreement for the Time effect.

Do they use a completely different approach, or is there any bug maybe?

**Comment by hugesingleton** [comment]
I received the following response from the author of the emmeans::joint_tests author. Maybe this will be informative for you regarding the drop1() function.
https://github.com/rvlenth/emmeans/issues/343

> […]
> You get very similar results from SAS if you specify the / E3 option to see the estimable functions; only their parameterization uses the last level as the reference level. These results are not surprising if you consider that marginal means are equally-weighted averages of predictions over the reference grid.
> But it is not at all surprising to me that drop1 would yield different tests, especially because the reduced models would not assign the same subject effects or weights in the GLM/GEE computations as are present in the full model.
>

**Comment by ekstroem** [comment]
There is nothing to fix as you are testing different contrasts. 

From the documentation of `joint_tests()` you also have the following (note that the `Results` variable is a covariate in this case):

> In models with only factors, no covariates, we believe these tests correspond to “type III” tests a la SAS, as long as equal-weighted averaging is used and there are no estimability issues. When covariates are present and interact with factors, the results depend on how the covariate is handled in constructing the reference grid. See the example at the end of this documentation. The point that one must always remember is that joint_tests always tests contrasts among EMMs, in the context of the reference grid, whereas type III tests are tests of model coefficients – which may or may not have anything to do with EMMs or contrasts.

The main effects are not always easily interpretable when interactions are present. The `Time` test from the `drop1()` call essentially examines if the 4 intercepts for the 4 time groups are the same when `Result=0`.  There are no values for `Result` close to 0 in the data frame so the grid created by `joint_tests()` is nowhere near testing the same contrast at `Result=0`.

However, you can force `joint_tests()` to give you the same result as for `drop1()` by specifying that you want the test at this particular grid point:

    joint_tests(m_geepack, at=list(Result=0))

which produces

    model term df1 df2 F.ratio p.value
    Time         3 Inf   2.162  0.0902

This matches the output from `drop1()`.
