### ISSUE TITLE
Are there plans to implement jackknife standard errors for `geeasy`? 

### ISSUE THREAD

**Issue by svteichman** [annennenne/geeasy#4]
Hello! 

We are using your package as a dependency for our package `enviromtx` and are wondering if you have any plans to implement jackknife standard errors in this package (as in the `geepack` package). We were originally using `geepack` because it lets us fit gee's and has implemented jackknife standard errors, however we were pointed to `geeasy` instead when we ran into issues with code hanging for `geepack` (see [this issue](https://github.com/hojsgaard/geepack/issues/21)). 

Thanks!
Sarah

**Comment by adw96** [comment]
Hi @annennenne and @ekstroem -- I love this package and am very grateful for its implementation and maintainence! 

I want to give a +1 / echo the request for jackknife standard errors. I also would really appreciate this functionality, as I work with a lot of small sample size experiments and have found that these give the best variance estimates in these settings. 

Are there any plans to implement this? 

Many thanks for creating this great open-source software package!

**Comment by hojsgaard** [comment]
Jackknife se's could certainly make their way into the package one day, but there are no specific plans. However, the following might be a simple way ahead:

```
get_jack_se <- function(object, dat){
    parm <- sapply(1:nrow(dat),
                   function(i){
                       dat.i <- dat[-i,]
                       coef(update(object, data=dat.i))
                   })
    parm <- t(parm)
    parm.mean <- apply(parm, 2, mean)
    
    parm.cent <- sapply(1:nrow(parm),
                        function(i){
                            parm[i, ] - parm.mean
                        })
    parm.cent <- t(parm.cent) 
    
    jack.var <- ((nrow(dat)-1) / nrow(dat)) * t(parm.cent) %*% parm.cent
    jack.se <- sqrt(diag(jack.var))
    jack.se
}


# EXAMPLE
data("respiratory")
respiratory$useid <- interaction(respiratory$center, respiratory$id)

# fit model
obj <- geelm(outcome ~ treat + sex + age + baseline, 
           data = respiratory, id = useid,
                      family = "binomial", corstr = "exchangeable")

dat <- respiratory
get_jack_se(obj, dat)
# compare with
summary(m) |> coef()

```

**Comment by svteichman** [comment]
Thank you for your help with this!
